"""
Integration test for Report Generation Tool
This actually generates a real PDF report to verify end-to-end functionality.
"""

import os
import sys
import json

# Add parent directory to path
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

from tools.report_tool import generate_farm_report, REPORTS_DIR


def test_generate_actual_report():
    """Integration test that generates a real PDF report"""
    print("\n🌱 Testing Report Generation Tool - Integration Test")
    print("=" * 60)

    # Sample farm report content
    report_content = """
# Farm Analysis Report

## Executive Summary
This is a comprehensive analysis of your farm operations for October 2024.

## Current Conditions

### Weather Analysis
- **Temperature**: 22°C (Optimal for most crops)
- **Rainfall**: 45mm this week
- **Humidity**: 65%
- **Conditions**: Favorable for planting

### Soil Health
- pH Level: 6.5 (Good)
- Nitrogen: Adequate
- Phosphorus: Moderate
- Potassium: Good

## Crop Status

| Crop    | Area (ha) | Status    | Expected Yield | Notes                |
|---------|-----------|-----------|----------------|----------------------|
| Maize   | 5.2       | Excellent | High           | Ready for harvest    |
| Beans   | 3.1       | Good      | Medium         | Monitor for pests    |
| Tomatoes| 1.5       | Fair      | Medium         | Needs more water     |
| Wheat   | 4.0       | Excellent | High           | Flowering stage      |

## Recommendations

### Immediate Actions (Next 7 Days)
1. **Harvest maize** - Optimal moisture content reached
2. **Apply fertilizer to tomatoes** - Nitrogen deficiency detected
3. **Inspect beans for pests** - Early signs of aphids
4. **Increase irrigation for tomatoes** - Soil moisture below optimal

### Short-term Planning (Next 30 Days)
- Prepare fields for next planting season
- Order seeds for rotation crops
- Service irrigation equipment
- Schedule soil testing

### Long-term Strategy
- Consider expanding tomato production area
- Implement drip irrigation system
- Explore organic certification options
- Diversify crop portfolio

## Market Insights

### Current Prices
- Maize: $250/ton (↑ 5% from last month)
- Beans: $800/ton (→ Stable)
- Tomatoes: $600/ton (↓ 3% from last month)
- Wheat: $280/ton (↑ 8% from last month)

### Recommendations
- **Sell maize now** - Prices are favorable
- **Hold beans** - Expect price increase next month
- **Sell tomatoes gradually** - Market is saturated

## Financial Summary

**Projected Revenue (This Season)**
- Maize: $6,500
- Beans: $4,960
- Tomatoes: $2,700
- Wheat: $4,480
- **Total**: $18,640

**Estimated Costs**
- Seeds & Inputs: $3,200
- Labor: $2,800
- Equipment: $1,500
- Other: $800
- **Total**: $8,300

**Net Profit**: $10,340

## Next Steps

1. Review and implement immediate action items
2. Schedule follow-up assessment in 2 weeks
3. Monitor weather forecasts daily
4. Track market prices for optimal selling times
5. Document all activities for future reference

---

*Report generated by Bloom AI Farming Assistant*
*For questions or support, contact your agricultural advisor*
"""

    print("\n📝 Generating report with sample farm data...")
    print("-" * 60)

    try:
        # Generate the report
        result = generate_farm_report(report_content)
        result_data = json.loads(result)

        if result_data.get("report_generated"):
            print("✅ Report generated successfully!")
            print(f"\n📄 Filename: {result_data['filename']}")
            print(f"🔗 Download URL: {result_data['download_url']}")
            print(f"💬 Message: {result_data['message']}")

            # Check if file actually exists
            filepath = os.path.join(REPORTS_DIR, result_data["filename"])
            if os.path.exists(filepath):
                file_size = os.path.getsize(filepath)
                print(f"\n✅ File verified on disk!")
                print(f"📁 Location: {filepath}")
                print(f"📊 Size: {file_size:,} bytes ({file_size/1024:.2f} KB)")
                print(
                    f"\n💡 You can open this file with any PDF viewer to verify the content."
                )
            else:
                print(f"\n❌ Warning: File not found at {filepath}")

        else:
            print("❌ Report generation failed!")
            print(f"Error: {result_data.get('error', 'Unknown error')}")
            print(f"Message: {result_data.get('message', 'No message')}")

    except Exception as e:
        print(f"❌ Test failed with exception: {e}")
        import traceback

        traceback.print_exc()

    print("\n" + "=" * 60)
    print("🎉 Integration test completed!")
    print(f"\n📂 All reports are saved in: {REPORTS_DIR}")


if __name__ == "__main__":
    test_generate_actual_report()
